DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS agreement CASCADE;
DROP TABLE IF EXISTS api_keys CASCADE;
DROP TABLE IF EXISTS flyway_schema_history CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS person_address CASCADE;
DROP TABLE IF EXISTS person_agreement CASCADE;
DROP TABLE IF EXISTS privilege CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS roles_privileges CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS users_roles CASCADE;

DROP VIEW IF EXISTS v_address_current;
DROP VIEW IF EXISTS v_agreement_current;
DROP VIEW IF EXISTS v_person_address_current;
DROP VIEW IF EXISTS v_person_current;



