DROP TABLE IF EXISTS address CASCADE;
DROP TABLE IF EXISTS agreement CASCADE;
DROP TABLE IF EXISTS flyway_schema_history CASCADE;
DROP TABLE IF EXISTS person CASCADE;
DROP TABLE IF EXISTS person_address CASCADE;
DROP TABLE IF EXISTS person_agreement CASCADE;
DROP TABLE IF EXISTS api_keys CASCADE;

DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS roles CASCADE;
DROP TABLE IF EXISTS privileges CASCADE;

