create table roles
(
    id          bigint      not null primary key,
    rolename    varchar(32) not null,
    description varchar(128),
    hash        int
);

create unique index roles_rolename_ix on roles (rolename);

ALTER TABLE roles
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME roles_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);