create table privilege
(
    id   bigint not null primary key,
    name varchar(24),
    hash int
);

create unique index privilege_name_ix on privilege (name);

ALTER TABLE privilege
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME privilege_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);
