create table roles_privileges
(
    id          bigint not null primary key,
    privilegeid bigint,
    roleid      bigint
);

create unique index roles_privileges_userid_ix on roles_privileges (roleid, privilegeid);

ALTER TABLE roles_privileges
ALTER
COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
        SEQUENCE NAME roles_privileges_id_seq
        START WITH 1
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
);



